### ISSUE TITLE
Experiment data round up

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/dng_zoe_exo_skl_2021#53]
- [ ] Record data in google drive on chlorine test done on 2022.02.16
- [x] Get and graph alkalinity data from bubble-spike-bubble test 2022.04.04
- [x] Get explanation of the salinity log and artificial seawater production
- [x] Create enrichment and natural CaCO3 stock log in google drive (dates, mass used to make acid and stocks)
- [x] Document cleaned vs uncleaned tubes
- [x] data for spec pH dye correction slope and intercept
- [x] confirm/debug z3 crab

**Comment by dmperez89** [comment]
["Unclean" water samples](https://docs.google.com/spreadsheets/d/1urG8w2E-KBRdHAAlZCh7i70T3IjWz7jBPwnaZHTJOsk/edit?usp=sharing)

["Unclean" zoea samples](https://docs.google.com/spreadsheets/d/1lQT5yMft5yGoLrIjskzPusVmzwJztG-YDyQx90k-UKQ/edit?usp=sharing)

Samples also noted in complete spreadsheets of ALL tubes

**Comment by dmperez89** [comment]
[Salinity/seawater creation log](https://docs.google.com/spreadsheets/d/1U5AxA2If1dD0EwpIzsXontOfcSk0Of31_ecTZe2R-sk/edit#gid=0)

**Comment by pmcelhany** [comment]
@dmperez89 sometime next week I need you to talk me through the salinity log so I know what it means.

**Comment by dmperez89** [comment]
[Stock recpies](https://docs.google.com/spreadsheets/d/1_ooXgWUISLdD5D2pW14imLIuXa3ZwMjX8A5B1pgylDc/edit#gid=0)

**Comment by pmcelhany** [comment]
@dmperez89 Where are the data for the spec dye correction slope and intercept ("double shot" data)?

**Comment by pmcelhany** [comment]
@dmperez89 I'd like to delete the "unclean" [water](https://docs.google.com/spreadsheets/d/1urG8w2E-KBRdHAAlZCh7i70T3IjWz7jBPwnaZHTJOsk/edit#gid=0) and [zoea](https://docs.google.com/spreadsheets/d/1lQT5yMft5yGoLrIjskzPusVmzwJztG-YDyQx90k-UKQ/edit#gid=0) sample files since they are redundant with data in the complete [water](https://docs.google.com/spreadsheets/d/1fceFyiKl-KJocRX8GXNVkTsXDV2sRsXp/edit#gid=1127115540) and [zoea](https://docs.google.com/spreadsheets/d/1M2xfWjR5hLXbmm2f64lxB00RvFK0lTB6/edit#gid=1127115540) sample files. It is best to have the data in just one file. I can sort out clean and unclean from the notes field now that I know it contains that info. Make sense?

**Comment by pmcelhany** [comment]
@dmperez89 in the [caco3 stock log](https://docs.google.com/spreadsheets/d/1_ooXgWUISLdD5D2pW14imLIuXa3ZwMjX8A5B1pgylDc/edit#gid=0), you made enriched stock on 2022.02.18 and on 2022.03.22. Did you combine these in the same bottle or did you keep the two batches in separate bottles? Please make a note about this in the document.

**Comment by pmcelhany** [comment]
@dmperez89 @michaelmaher114 
[Here](https://docs.google.com/presentation/d/1vm4M1EeUOzZU98OVtngVaLN45NcHjCxJCCRx6Z1oQm0/edit#slide=id.g124645ba3bd_0_0) is the summary of sample counts from the experiment based on the water and zoea sample log data. Does this seem correct? Does this include the live zoea that were preserved on the last day of the experiment?

**Comment by dmperez89** [comment]
@pmcelhany 
We haven't done double shots recently, but I can probably do them and then fix the intercepts retroactively.
That's fine to delete the redundant files. I only made them since it was mentioned in the checklist.
The new enriched stock was added to the same bottle as the original enriched stock, but there wasn't any enriched stock remaining. Or, if there was any, it was only a small drop amounting to a few microliters. I will add this info to the log. 
That summary sounds about right. I did a rough count of number of boxes after we preserved (so yes, the live at the end should be included) and I remember it being more than 2,500. 2,817 seems a bit higher than I remember, but it's absolutely plausible.

**Comment by pmcelhany** [comment]
@dmperez89 We need to do double shots for every batch of dye that we use. Add the worksheet for the slope\intercept calcs to the spec_ph data folder.

**Comment by pmcelhany** [comment]
@dmperez89 [This file](https://github.com/NWFSC-OA-lab/dng_zoe_exo_skl_2022/blob/main/data/dng_zoea_well_2022/z3_crab.csv) has data on two crabs the are recorded as molting to z3. One of them seems very unlikely as there are only 7 days between z2 and z3, but the other seems plausible (18 days). However, the 18 day crab is recorded as molting on the last day of the experiment, which makes me suspect typo. Can you look into these two crabs? My cut off for ignoring multiple observations of discarded exoskeletons is 5 days, which seems plenty generous as it allows for the molt to possibly transfer though one feeding cycle.

**Comment by dmperez89** [comment]
@pmcelhany I looked through the data and I think I have an answer, though it does require us to make an educated guess. I agree that it's highly unlikely the crab in question (CH06_N_104_2022_02_24) molted twice in seven days. However, all the crabs surrounding it molted at some point EXCEPT for the one that was consistently right next to it (CH06_N_105_2022_02_24). Therefore I think we can assume that one of those molt days was destined for the latter. Unfortunately the molt from 3/17 wasn't preserved, so we don't have any other documentation on it. However, the molt in question from 3/23 was preserved, and it was marked as coming from CH06_N_104_2022_02_24. Now, it's entirely possible that it was marked incorrectly on the data sheets twice. But I think we could gather that: 

CH06_N_105_2022_02_24 molted from Z1 to Z2 on 3/17
CH06_N_104_2022_02_24 molted from Z1 to Z2 on 3/23
Alternatively, if we don't feel great about that, we can mark them both removed from the dataset. Let me know what you'd like me to do and I can update the data sheets accordingly. 

I also remember that molt on the last day! There were actually two, because there was also one in the enrichment set. So not a typo, they were just keeping us on our toes until the very end.

**Comment by pmcelhany** [comment]
What you suggest makes sense. Change the data sheets to reflect 
CH06_N_105_2022_02_24 molted from Z1 to Z2 on 3/17
CH06_N_104_2022_02_24 molted from Z1 to Z2 on 3/23

So it looks like we did manage to get on Z3 crab on the very last day!

**Comment by dmperez89** [comment]
Done. And yes, I thought that one Z3 molt was pretty exciting!

**Comment by dmperez89** [comment]
[Salinity/seawater SOP here](https://docs.google.com/document/d/1VFAsUwcaqn_2Cuo1oLUYBChAapSsy-CDIgaMRV1RafE/edit)

**Comment by pmcelhany** [comment]
The seawater report looks good. I added a few questions in the comments.

**Comment by pmcelhany** [comment]
Moved remaining task to a new issue
